import assert from "node:assert/strict";
import { mkdir, mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";

import {
  findInstalledCodexRuntimeDistRoots,
  patchRuntimeIdentityPromptSource,
  resolveLiveIdentityDistRoots,
} from "../tools/apply-live-gpao-t-runtime-identity-prompt-patch.mjs";

const source = [
  "You are a personal agent running inside OpenClaw. OpenClaw has dynamic tools for OpenClaw-owned messaging, cron, sessions, media, gateway, and nodes.",
  "Deferred searchable OpenClaw dynamic tools available:",
  "Use OpenClaw `sessions_spawn` only for OpenClaw or ACP delegation",
  "OpenClaw will deliver it through the active source conversation.",
  "## OpenClaw Workspace Context",
  "OpenClaw runtime context for this turn:",
  "Treat this OpenClaw-provided context as supporting project/user reference for the current request.",
  "OpenClaw assembled context for this turn:",
  "OpenClaw delivery metadata:",
  "## OpenClaw Skills",
  "OpenClaw loaded these user-editable workspace files for the current turn.",
  "## OpenClaw Workspace Instructions",
  "OpenClaw loaded these workspace instruction files from the active agent workspace. Internalize and follow them accordingly.",
  "## OpenClaw Agent Soul",
  "OpenClaw loaded these workspace instruction files from the active agent workspace. They are the canonical definitions of who you are, how you think and work, and the human you work alongside. Internalize and follow them accordingly.",
  "## OpenClaw Heartbeat Workspace",
  "## OpenClaw Workspace Memory",
  "OpenClaw does not paste its contents into native Codex turns;",
  "The following JSON is generated by OpenClaw out-of-band.",
  "OpenClaw is capped by agents.defaults.contextTokens, so raise that cap if you want to use more of the model context window",
  "OpenClaw is using the configured model context limit for this model, so raise contextWindow/contextTokens if it is set too low",
  "OpenClaw is capped by agents.defaults.contextTokens. Raise that cap.",
  "OpenClaw is using the configured model context limit for this model. Raise contextWindow/contextTokens or choose a larger model.",
  "This looks like a local model endpoint. Raise the server/model context limit or choose a larger model. OpenClaw local/self-hosted runs work best at 32000+ tokens.",
  "Run `openclaw configure`",
  "run `openclaw configure`",
  "openclaw models auth login",
].join("\n");

test("runtime prompt identifies the live agent as GPAO-T", () => {
  const result = patchRuntimeIdentityPromptSource(source);
  assert.equal(result.replacements.length, 27);
  assert.match(result.source, /live companion agent of nBeAI\. GPAO-T/);
  assert.match(result.source, /Deferred searchable GPAO-T dynamic tools available/);
  assert.match(result.source, /## GPAO-T Workspace Instructions/);
  assert.match(result.source, /## GPAO-T Agent Identity/);
  assert.match(result.source, /## GPAO-T Workspace Memory/);
  assert.match(result.source, /GPAO-T compatibility runtime out-of-band/);
  assert.match(result.source, /GPAO-T is capped by the current runtime contextTokens setting/);
  assert.match(result.source, /GPAO-T is using the configured model context limit/);
  assert.match(result.source, /GPAO-T Settings > 모델 연결/);
  assert.match(result.source, /gpao-t models auth login/);
  assert.doesNotMatch(result.source, /personal agent running inside OpenClaw/);
  assert.doesNotMatch(result.source, /## OpenClaw Agent Soul/);
  assert.doesNotMatch(result.source, /OpenClaw is capped/);
  assert.doesNotMatch(result.source, /openclaw configure/);
});

test("runtime identity prompt patch is idempotent", () => {
  const once = patchRuntimeIdentityPromptSource(source).source;
  const twice = patchRuntimeIdentityPromptSource(once);
  assert.equal(twice.source, once);
  assert.deepEqual(twice.replacements, []);
});

test("runtime identity patch discovers the installed Codex compatibility runtime", async () => {
  const stateHome = await mkdtemp(join(tmpdir(), "gpao-t-identity-runtime-"));
  const pluginDist = join(
    stateHome,
    "npm/projects/codex-runtime/node_modules/@openclaw/codex/dist",
  );
  await mkdir(pluginDist, { recursive: true });
  await writeFile(join(pluginDist, "thread-lifecycle.js"), source);

  assert.deepEqual(
    await findInstalledCodexRuntimeDistRoots({ stateHome }),
    [pluginDist],
  );
});

test("runtime identity roots include both GPAO-T core and installed Codex runtime", async () => {
  const stateHome = await mkdtemp(join(tmpdir(), "gpao-t-identity-roots-"));
  const primaryDist = join(stateHome, "current/compatibility/gpao-t/dist");
  const pluginDist = join(
    stateHome,
    "npm/projects/codex-runtime/node_modules/@openclaw/codex/dist",
  );
  await mkdir(primaryDist, { recursive: true });
  await mkdir(pluginDist, { recursive: true });

  assert.deepEqual(
    await resolveLiveIdentityDistRoots({ primaryDist, stateHome, extraDists: "" }),
    [primaryDist, pluginDist],
  );
});
